---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`suma_longitudes` es una función"
  checked: true
- value: "`suma_longitudes` tiene dos parámetros"
  checked: true
- value: "`suma_longitudes` puede ser invocada con 2 argumentos"
  checked: true
- value: si escribimos `suma_longitudes("aprendiendo", "programación")`, `"aprendiendo"`
    será el primer argumento y `"programación"`, el segundo
  checked: true
name: Funciones con agujeritos
