---
name: Funciones y Parámetros
locale: es
type: learning
beta: false
teacher_info: ''
language: python3
id_format: "%05d"
order:
- 14
- 15
- 17
- 16
- 18
- 19
- 4
- 5
- 8
- 9
- 10
- 12
- 13
- 11
private: false
