---
locale: es
tags: []
layout: input_bottom
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: true
choices: []
name: Entre los números y la pared
