---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: "¡Bien! Estas semanejanzas no son casuales: ¡para definir funciones
  hay que seguir algunas reglas!\n\n1. Toda definición debe arrancar con la palabra
  reservada `def` (abreviatura de _definir_ en inglés);\n2. luego, deben ir el nombre
  de la función;\n3. luego, entre paréntesis, deben ir los _parámetros_ que la función
  va a tener y que más tarde le permitirán recibir _argumentos_ al invocarla;\n4.
  luego, deben ir dos puntos (`:`) antes de terminar esta primera línea (también llamada
  _cabecera_);\n5. Las siguientes líneas (también llamadas _cuerpo_) deben empezar
  tabuladas (es decir, no directamente contra el margen, usando la tecla `Tab ↹`);\n6.
  La última línea debe empezar con  `return`, seguido de lo que queremos que devuelva
  nuestra función.\n\n\nUff, ¡muchas reglas :tired_face:! No te preocupes, de a poco
  las iremos dominando. \n\n\n"
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas empiezan con `def` seguido del nombre de la función
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas empiezan con `def` seguido de dos puntos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas tienen un `return` en la primera línea
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas tienen un `return` en la última línea
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas terminan la primera línea con en dos puntos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ambas arrancan la segunda línea contra el margen
  checked: false
name: El juego de los parecidos
